defmodule ChatOverlay.Crypto do
  @moduledoc """
  Cryptographic primitives for capability tokens, AEAD encryption of platform tokens,
  and OAuth PKCE / state protection.

  Uses Erlang/OTP `:crypto` and `Plug.Crypto.secure_compare/2` without external dependencies.
  Fulfills SEC-12, SEC-14, SEC-15 and ADR 0003.
  """

  @aead_cipher :aes_256_gcm
  @iv_bytes 12
  @tag_bytes 16
  @key_bytes 32

  # Capability Tokens (SEC-14, ADR 0003)

  @doc """
  Generates a 32-byte cryptographically secure random token, URL-safe without padding.
  Used as capability tokens for OBS browser source authentication.
  """
  @spec generate_capability_token() :: String.t()
  def generate_capability_token do
    :crypto.strong_rand_bytes(32)
    |> Base.url_encode64(padding: false)
  end

  @doc """
  Computes a SHA-256 hex digest of a capability token.
  The hash is stored in configurations/databases so that plaintext tokens
  cannot be derived if the storage is inspected.
  """
  @spec hash_token(String.t()) :: String.t()
  def hash_token(token) when is_binary(token) do
    :crypto.hash(:sha256, token)
    |> Base.encode16(case: :lower)
  end

  @doc """
  Verifies a plaintext token against an expected SHA-256 hex hash using constant-time
  comparison (`Plug.Crypto.secure_compare/2`) to prevent timing attacks.
  """
  @spec verify_token(String.t(), String.t()) :: boolean()
  def verify_token(provided_token, expected_hash)
      when is_binary(provided_token) and is_binary(expected_hash) do
    provided_hash = hash_token(provided_token)

    if byte_size(provided_hash) == byte_size(expected_hash) do
      Plug.Crypto.secure_compare(provided_hash, expected_hash)
    else
      false
    end
  end

  def verify_token(_, _), do: false

  # Symmetric AEAD Encryption (AES-256-GCM) (SEC-15)

  @doc """
  Encrypts plaintext using AES-256-GCM with authenticated additional data (AAD).
  Generates a random 12-byte IV for every encryption.
  Returns a versioned URL-safe string: `"v1:<base64(iv <> tag <> ciphertext)>"`.
  """
  @spec encrypt_aead(binary(), binary(), binary()) :: {:ok, String.t()} | {:error, term()}
  def encrypt_aead(plaintext, key, aad \\ "")
      when is_binary(plaintext) and is_binary(key) and is_binary(aad) do
    with {:ok, key_32} <- normalize_key(key) do
      iv = :crypto.strong_rand_bytes(@iv_bytes)

      case :crypto.crypto_one_time_aead(@aead_cipher, key_32, iv, plaintext, aad, true) do
        {ciphertext, tag} ->
          payload = iv <> tag <> ciphertext
          encoded = "v1:" <> Base.url_encode64(payload, padding: false)
          {:ok, encoded}

        _other ->
          {:error, :encryption_failed}
      end
    end
  end

  @doc """
  Decrypts an AEAD payload generated by `encrypt_aead/3`.
  Validates integrity tag and AAD. Returns `{:ok, plaintext}` or `{:error, :corrupted_or_invalid_key}`.
  """
  def decrypt_aead(payload, key, aad \\ "")

  def decrypt_aead("v1:" <> encoded_payload, key, aad)
      when is_binary(key) and is_binary(aad) do
    with {:ok, key_32} <- normalize_key(key),
         {:ok, payload} <- Base.url_decode64(encoded_payload, padding: false),
         true <- byte_size(payload) >= @iv_bytes + @tag_bytes do
      <<iv::binary-size(@iv_bytes), tag::binary-size(@tag_bytes), ciphertext::binary>> = payload

      case :crypto.crypto_one_time_aead(@aead_cipher, key_32, iv, ciphertext, aad, tag, false) do
        plaintext when is_binary(plaintext) ->
          {:ok, plaintext}

        :error ->
          {:error, :corrupted_or_invalid_key}
      end
    else
      _ -> {:error, :invalid_payload}
    end
  end

  def decrypt_aead(_, _, _), do: {:error, :invalid_payload_format}

  # OAuth PKCE & Signed State (SEC-14)

  @doc """
  Generates a PKCE code_verifier and code_challenge using SHA-256 (S256).
  """
  @spec generate_pkce() :: %{verifier: String.t(), challenge: String.t(), method: String.t()}
  def generate_pkce do
    verifier =
      :crypto.strong_rand_bytes(32)
      |> Base.url_encode64(padding: false)

    challenge =
      :crypto.hash(:sha256, verifier)
      |> Base.url_encode64(padding: false)

    %{verifier: verifier, challenge: challenge, method: "S256"}
  end

  @doc """
  Signs a state map with HMAC-SHA256 using a server secret key.
  Includes a timestamp for freshness verification.
  """
  @spec sign_oauth_state(map(), binary()) :: String.t()
  def sign_oauth_state(data, secret_key) when is_map(data) and is_binary(secret_key) do
    payload_map = Map.put(data, "ts", System.system_time(:second))
    json_payload = ChatOverlay.JSON.encode(payload_map)
    signature = :crypto.mac(:hmac, :sha256, secret_key, json_payload)

    Base.url_encode64(json_payload, padding: false) <>
      "." <> Base.url_encode64(signature, padding: false)
  end

  @doc """
  Verifies an OAuth state string. Checks HMAC signature in constant time
  and verifies that it has not expired (default: 600 seconds = 10 minutes).
  """
  @spec verify_oauth_state(String.t(), binary(), integer()) ::
          {:ok, map()} | {:error, :expired | :invalid_signature | :malformed}
  def verify_oauth_state(signed_state, secret_key, max_age_seconds \\ 600)
      when is_binary(signed_state) and is_binary(secret_key) do
    case String.split(signed_state, ".", parts: 2) do
      [encoded_payload, encoded_sig] ->
        with {:ok, json_payload} <- Base.url_decode64(encoded_payload, padding: false),
             {:ok, expected_sig} <- Base.url_decode64(encoded_sig, padding: false),
             calculated_sig = :crypto.mac(:hmac, :sha256, secret_key, json_payload),
             true <- Plug.Crypto.secure_compare(calculated_sig, expected_sig),
             {:ok, data} when is_map(data) <- ChatOverlay.JSON.decode(json_payload),
             ts when is_integer(ts) <- data["ts"] do
          now = System.system_time(:second)

          if now - ts >= 0 and now - ts <= max_age_seconds do
            {:ok, data}
          else
            {:error, :expired}
          end
        else
          false -> {:error, :invalid_signature}
          _ -> {:error, :malformed}
        end

      _ ->
        {:error, :malformed}
    end
  end

  # Helpers

  defp normalize_key(key) when byte_size(key) == @key_bytes, do: {:ok, key}

  defp normalize_key(key) when is_binary(key) and byte_size(key) > 0 do
    # If key is not exactly 32 bytes, derive a 32-byte key via SHA-256
    {:ok, :crypto.hash(:sha256, key)}
  end

  defp normalize_key(_), do: {:error, :invalid_key}
end
